export const Routes = {
  // Auth
  SPLASH1: '/splash1',
  SPLASH2: '/splash2',
  SPLASH3: '/splash3',
  SPLASH4: '/splash4',
  SPLASH5: '/splash5',
  ONBOARDING: '/onboarding',
  LOGIN: '/login',
  OTP: '/otp',
  SIGNUP: '/signup',
  // Main tabs
  HOME: '/home',
  DASHBOARD: '/dashboard',
  MARKET: '/market',
  ORDERS: '/orders',
  CATEGORIES: '/categories',
  BRANDS: '/brands',
  CART: '/cart',
  PROFILE: '/profile',
  // Buy flow
  BUY_1: '/buy/1',
  BUY_2: '/buy/2',
  BUY_3: '/buy/3',
  BUY_4: '/buy/4',
  BUY_5: '/buy/5',
  // Sell flow
  SELL_1: '/sell/1',
  SELL_2: '/sell/2',
  SELL_3: '/sell/3',
  SELL_4: '/sell/4',
  SELL_5: '/sell/5',
  // SIP flow
  SIP_1: '/sip/1',
  SIP_2: '/sip/2',
  SIP_3: '/sip/3',
  SIP_4: '/sip/4',
  SIP_5: '/sip/5',
  KYC_VERIFICATION: '/kyc-verification',
  PAYMENT_METHODS: '/payment-methods',
  REWARDS: '/rewards',
  SECURITY: '/security',
  HELP_CENTER: '/help-center',
  TERMS: '/terms',
  // Modals
  NOTIFICATIONS: '/notifications',
  PARTNER: '/partner',
  NEARBY: '/nearby',
  BANK_VERIFY: '/bank-verify',
  BANK_VERIFY_LOADING: '/bank-verify-loading',
} as const;

export const AutoAdvanceDelays = {
  SPLASH_1: 4000,
  SPLASH_2: 8000,
  SPLASH_3: 3500,
  SPLASH_4: 4000,
  SPLASH_5: 4000,
  BANK_VERIFY_LOAD: 3000,
  BUY_4: 4000,
  SELL_4: 4000,
  SIP_4: 4000,
  POPUP: 5000,
} as const;
